In [1]:
#Numpy has one data structure that is n-dimesnionl array
print("Numpy Campus X")

Numpy Campus X


In [39]:
#this is the sytax to include numpy in ur project

In [41]:
import numpy as np

In [43]:
x=np.array({})

In [45]:
arr1=np.array([1,2,3,4])

In [57]:
arr1

array([[1, 2, 3],
       [2, 5, 6]])

In [59]:
type(arr1)

numpy.ndarray

In [83]:
arr2=np.array([[1,2,3],[2,5,6]])
arr2

array([[1, 2, 3],
       [2, 5, 6]])

In [85]:
arr3=np.zeros((2,3))
arr3



array([[0., 0., 0.],
       [0., 0., 0.]])

In [105]:
arr10=np.arange(10)
arr10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
ls=[1,2,3]
ls

[1, 2, 3]

In [94]:
ls

[1, 2, 3]